apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - image: quay.io/jotak/nginx-hello:0.2
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    securityContext:
      privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: server

